#!/usr/bin/env bash
#
# Amby AI Video Service - Docker setup
#
# One-shot setup for the containerized app on any machine.
# PREREQUISITE: Docker + Docker Compose must already be installed and running.
# This script does NOT install Docker - it checks for it and asks you to install
# it first if it is missing.
#
# What it does:
#   1. Verifies Docker + Docker Compose are installed and the daemon is running.
#   2. Interactively collects credentials into .env.docker (if not already set up).
#   3. Builds the image (deps + ffmpeg are pulled inside the image).
#   4. Starts the stack (app + the workflow Postgres) and waits until healthy.
#
# Usage:
#   ./docker-setup.sh                 # check, configure, build, run
#   ./docker-setup.sh --reconfigure   # re-enter the .env.docker values
#   ./docker-setup.sh --rebuild       # rebuild the image from scratch (no cache)
#   ./docker-setup.sh --down          # stop and remove the stack
#   ./docker-setup.sh --help
#
set -euo pipefail

ENV_FILE=".env.docker"
APP_URL="http://localhost:3000"

log()  { printf '\n==> %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }
err()  { printf 'ERROR: %s\n' "$*" >&2; }

REBUILD=0; DOWN=0; RECONFIGURE=0
for a in "$@"; do
  case "$a" in
    --rebuild)     REBUILD=1 ;;
    --down)        DOWN=1 ;;
    --reconfigure) RECONFIGURE=1 ;;
    --help|-h)     sed -n '2,26p' "$0" | sed 's/^#\{0,1\} \{0,1\}//'; exit 0 ;;
    *)             err "unknown option: $a (try --help)"; exit 1 ;;
  esac
done

# Must run from the project root.
if [ ! -f Dockerfile ] || [ ! -f docker-compose.yml ]; then
  err "Run this from the project root (Dockerfile / docker-compose.yml not found here)."
  exit 1
fi

# --down short-circuit.
if [ "$DOWN" -eq 1 ]; then
  log "Stopping the stack..."
  docker compose down
  exit 0
fi

# 1. Check Docker (do not install).
log "Checking Docker..."
if ! command -v docker >/dev/null 2>&1; then
  err "Docker is not installed."
  info "Please install Docker first, then run this script again:"
  info "  https://docs.docker.com/get-docker/"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose (v2) is not available."
  info "Install/upgrade Docker (it includes the Compose plugin), then run this again:"
  info "  https://docs.docker.com/get-docker/"
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "Docker is installed but the daemon is not reachable."
  info "Start Docker Desktop (macOS/Windows) or the Docker service (Linux: 'sudo systemctl start docker'),"
  info "then run this script again. On Linux you may also need to be in the 'docker' group."
  exit 1
fi
info "Docker and Compose are ready."

# 2. Configure .env.docker (interactive).
# Appends VAR=value from an interactive prompt; supports an optional default.
prompt_var() {
  local var="$1" desc="$2" def="${3:-}" val=""
  if [ -n "$def" ]; then
    read -r -p "    $desc [$def]: " val
    val="${val:-$def}"
  else
    while [ -z "$val" ]; do
      read -r -p "    $desc: " val
      [ -z "$val" ] && info "(required - please enter a value)"
    done
  fi
  printf '%s=%s\n' "$var" "$val" >> "$ENV_FILE"
}

if [ -f "$ENV_FILE" ] && [ "$RECONFIGURE" -eq 0 ]; then
  log "Using existing $ENV_FILE (run with --reconfigure to re-enter values)."
else
  if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
    info "Backed up existing $ENV_FILE"
  fi
  log "Configuring $ENV_FILE - enter your credentials:"
  : > "$ENV_FILE"
  echo "# Generated by docker-setup.sh" >> "$ENV_FILE"

  info "App database (Neon Postgres):"
  prompt_var DATABASE_URL "DATABASE_URL (pooled Neon connection string)"
  prompt_var DIRECT_URL   "DIRECT_URL (direct/non-pooled Neon connection string)"

  info "Auth:"
  if command -v openssl >/dev/null 2>&1; then
    printf 'NEXTAUTH_SECRET=%s\n' "$(openssl rand -base64 32)" >> "$ENV_FILE"
    info "NEXTAUTH_SECRET auto-generated."
  else
    prompt_var NEXTAUTH_SECRET "NEXTAUTH_SECRET (random 32+ character string)"
  fi
  prompt_var NEXTAUTH_URL "NEXTAUTH_URL" "http://localhost:3000"

  info "AWS S3 (video storage):"
  prompt_var AWS_ACCESS_KEY_ID     "AWS_ACCESS_KEY_ID"
  prompt_var AWS_SECRET_ACCESS_KEY "AWS_SECRET_ACCESS_KEY"
  prompt_var AWS_REGION            "AWS_REGION" "ap-south-1"
  prompt_var AWS_S3_BUCKET         "AWS_S3_BUCKET"

  info "AI providers:"
  prompt_var OPENAI_API_KEY "OPENAI_API_KEY"
  prompt_var GROQ_API_KEY   "GROQ_API_KEY"

  info "Pipeline:"
  prompt_var CHUNK_MINUTES "CHUNK_MINUTES (minutes of video per transcription chunk)" "10"

  log "Wrote $ENV_FILE"
fi

# 3. Build.
log "Building the image (first run pulls dependencies + ffmpeg; can take several minutes)..."
if [ "$REBUILD" -eq 1 ]; then
  docker compose build --no-cache
else
  docker compose build
fi

# 4. Start.
log "Starting the stack..."
docker compose up -d

# 5. Wait for health.
if command -v curl >/dev/null 2>&1; then
  log "Waiting for the app to become healthy..."
  ok=0
  for _ in $(seq 1 40); do
    if curl -fsS "$APP_URL/api/health" >/dev/null 2>&1; then ok=1; break; fi
    sleep 3
  done
  if [ "$ok" -eq 1 ]; then
    log "Ready. The app is running at $APP_URL"
  else
    err "The app did not report healthy in time. Check logs below."
  fi
else
  log "Stack started. (Install 'curl' to auto-verify health.) App should be at $APP_URL"
fi

cat <<EOF

Useful commands:
  docker compose logs -f app     follow the app logs
  docker compose ps              container status
  ./docker-setup.sh --down       stop and remove the stack
  ./docker-setup.sh --rebuild    rebuild the image from scratch
EOF
